version: '3'

services:
  frontend:
    build: frontend
    ports:
      - '3030:3000'
      - '8080:80'
    depends_on:
      - backend

  backend: 
    build: backend
    ports:
      - '3000:3000'
    depends_on:
      - redis_db

  redis_db:
    image: redis:alpine
    container_name: redis_db
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data

# EOF