name: Build & Publish docker images to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-1"                     # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: "url-shortner"              # set this to your Amazon ECR repository name
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in

permissions:
  contents: read

jobs:
  build-frontend:
    name: Build frontend docker image
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Build & Tag Image
        env:
          IMAGE_TAG: backend:${{ github.sha }}
        run: |
          echo "Building Frontend Docker Image"
          echo "IMAGE_TAG: ${IMAGE_TAG}"
          docker build . -t $IMAGE_TAG