name: Build & Publish docker images to Amazon ECR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-frontend:
    name: Build frontend docker image
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build & tag frontend Image
      working-directory: ./frontend/
      env:
        IMAGE_TAG: backend:${{ github.sha }}
      run: |
        echo "Current Directory: $(pwd)"
        echo "Building Frontend Docker Image"
        echo "IMAGE_TAG: ${IMAGE_TAG}"
        docker build . -t $IMAGE_TAG